apiVersion: harness.io/v1
kind: API
type: openapi
identifier: joelauthpoc1
name: joel-auth-poc1
owner: user:account/joel.j.gaikwad@avyka.com
spec:
  lifecycle: experimental
  sourceCode:
    provider: Github
    repoName: hello-joel-api
    connectorRef: account.joelgithubconnector
    branch: main
    monoRepo: false
    url: https://github.com/joelgaikwad-125/hello-joel-api/tree/main
  definition:
    $text: https://github.com/joelgaikwad-125/hello-joel-api/blob/main/api-definition.yaml
metadata:
  description: API for CRUD
  tags:
  - idp
  - api
