apiVersion: harness.io/v1
kind: API
type: openapi
identifier: joelauthpoc1
name: joel-auth-poc1
owner: user:account/joel.j.gaikwad@avyka.com
spec:
  lifecycle: experimental
  definition:
    $text: ./api-definition.yaml
metadata:
  description: API for CRUD
  tags:
  - idp
  - api
