apiVersion: harness.io/v1
kind: Component
type: service
identifier: joelidppocjava
name: joel-idp-poc-java
owner: user:account/joel.j.gaikwad@avyka.com
orgIdentifier: default
projectIdentifier: Joel_Playground
spec:
  lifecycle: experimental
  sourceCode:
    provider: Github
    repoName: hello-joel-api
    connectorRef: joelgithubconnector
    branch: main
    monoRepo: false
    url: https://github.com/joelgaikwad-125/hello-joel-api/tree/main
  consumesApis:
  - api:account.default.Joel_Playground/joelidpjavaauth
metadata:
  annotations:
    harness.io/pipelines: |
      STO: https://app.harness.io/ng/account/gLXLxjTmQhGmdJXhAORKag/module/ci/orgs/default/projects/Joel_Playground/pipelines/joelidppipeline/pipeline-studio/?storeType=INLINE
      backstage.io/techdocs-ref: dir:.
  tags:
  - idp
  - java
