apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hello-joel-service
  description: Simple Hello Joel Service
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: user:guest
  lifecycle: development
  providesApis:
    - hello-joel-api
