apiVersion: harness.io/v1
kind: Component
type: service
identifier: joelidppocjava
name: joel-idp-poc-java
owner: user:account/joel.j.gaikwad@avyka.com
orgIdentifier: default
projectIdentifier: Joel_Playground
spec:
  lifecycle: experimental
  sourceCode:
    provider: Github
    repoName: hello-joel-api
    connectorRef: joelgithubconnector
    branch: main
    monoRepo: false
    url: https://github.com/joelgaikwad-125/hello-joel-api/tree/main
  consumesApis:
  - api:account.default.Joel_Playground/joelidpjavaauth
metadata:
  annotations:
    backstage.io/techdocs-ref: dir:.
    backstage.io/source-location: url:https://github.com/joelgaikwad-125/hello-joel-api
  tags:
  - idp
  - java
